# sample file: https://docs.netlify.com/configure-builds/file-based-configuration/#sample-netlify-toml-file
[build]
  base = ""
  publish = ""

  # Default build command.
  command = "echo 'foo'"

[[redirects]]
  from = "/*"
  to = "https://www.voxels.com/play?coords=W@5083W,1646N"